database:
    db_connection_file: 'dbconnection.json'
csv_paths:
    training_paths: 'training_qrcodes.csv'
    testing_paths: 'testing_qrcodes.csv'
scans:
    scan_amount : 3000
calibration:
    calibration_file: 'calibration.txt'
data:
    dataset: 'anon-pcd-version5.0'
paths:
    target_path: 'new_data'
