name: project_environment
channels:
  - conda-forge
dependencies:
  - setuptools=50.3.0
  - wheel=0.35.1
  - python=3.7
  - pip
  - wandb
  - pip:
    - azureml-core==1.21.0
    - numpy==1.18.5
    - pandas==0.23.4
    - imgaug==0.4.0
    - azureml-defaults
    - glob2==0.7
    - tensorflow==2.3.1
    - tensorflow-addons==0.11.2
    - pyyaml
    - bunch==1.0.1
    - scikit-learn==0.22.2.post1
    - PyJWT==1.7.1
    - azureml-dataprep[pandas,fuse]==2.8.2
    - evidential-deep-learning