version: 1

formatters:
  lowdetail:
    format: "%(asctime)s - %(levelname)s - %(message)s"
  highdetail:
    format: "%(asctime)s - %(levelname)s - %(message)s - %(pathname)s: line %(lineno)d"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: highdetail
    stream: ext://sys.stdout

  file:
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    formatter: highdetail
    filename: logs/logs.log
    backupCount: 10
    encoding: utf8

root:
  level: NOTSET
  handlers: [console, file]
  propagate: yes