name: CGM_QA_Pipeline
channels:
  - conda-forge
dependencies:
  - setuptools=50.3.0
  - wheel=0.36.2
  - python=3.7
  - pip
  - nb_conda_kernels==2.2.1
  - scikit-image
  - pip:
    - azure-cli==2.25.0
    - azureml-sdk==1.21.0
    - matplotlib==3.3.4
    - glob2==0.7
    - tensorflow==2.4.2
    - tensorflow-addons==0.13.0
    - bunch==1.0.1
    - cgmzscore==2.0.3
    - scikit-learn==0.22.2.post1