name: CGM_QA_Pipeline
channels:
  - conda-forge
dependencies:
  - python=3.7
  - nb_conda_kernels==2.2.1
  - scikit-image==0.17.2
  - matplotlib==3.3.3
  - glob2==0.7
  - papermill==2.2.2
  - nbcovert==6.0.7
  - pip:
    - azure-cli==2.0.69
    - azureml-sdk[notebooks,automl]==1.18.0
    - tensorflow-addons==0.11.2
