trigger:
  branches:
    include:
    - releases/*

pr: none

jobs:
- job: EvaluationJob
  timeoutInMinutes: 300
  cancelTimeoutInMinutes: 2

  pool:
    vmImage: 'Ubuntu-20.04'

  steps:

  - bash: |
      set -euox pipefail
      cd src/common/evaluation/QA
      source /usr/share/miniconda/etc/profile.d/conda.sh
      conda env create -f environment.yml
      conda activate CGM_QA_Pipeline
      jupyter kernelspec list
    displayName: 'Environment Creation'

  - bash: |
      az login -t $(sptenent) --service-principal -u $(spidentity) --password $(spsecret)
      az account set --subscription $(subscriptionid)
    displayName: 'Azure Login'

  - bash: |
      set -euox pipefail
      cd src/common/evaluation/QA
      source /usr/share/miniconda/etc/profile.d/conda.sh
      conda activate CGM_QA_Pipeline
      python auth.py -sid $(subscriptionid) -rg $(RESOURCE_GROUP) -wn $(WORKSPACE_NAME)
    displayName: 'Saving Workspace Config'

  - bash: |
      set -euox pipefail
      cd src/common/evaluation/QA/eval_depthmap_models
      source /usr/share/miniconda/etc/profile.d/conda.sh
      conda activate CGM_QA_Pipeline
      python eval_main.py --qa_config_module qa_config_42c4ef33
      python eval_main.py --qa_config_module qa_config_cb44f6db
      ls -l
    displayName: 'Depthmap Height Model Evaluation'

  - bash: |
      set -euox pipefail
      cd src/common/evaluation/QA/eval_depthmap_models
      source /usr/share/miniconda/etc/profile.d/conda.sh
      conda activate CGM_QA_Pipeline
      python combine_results.py
      ls -l
    displayName: 'Combine results'

    - bash: |
      set -euox pipefail
      cd src/common/evaluation/QA/eval_depthmap_models
      source /usr/share/miniconda/etc/profile.d/conda.sh
      conda activate CGM_QA_Pipeline
      python eval_main.py --qa_config_module qa_config_weight
      ls -l
    displayName: 'Depthmap Weight Model Evaluation'

  - bash: |
      set -euox pipefail
      cd src/common/evaluation/QA/eval-standardisation-test
      source /usr/share/miniconda/etc/profile.d/conda.sh
      conda activate CGM_QA_Pipeline
      papermill eval_notebook.ipynb standardisation-test_output.ipynb --log-output --no-progress-bar -k python3
      jupyter nbconvert --to html standardisation-test_output.ipynb
      ls -l
    displayName: 'Standardisation Test Model Evaluation'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        src/common/evaluation/QA/eval_depthmap_models/depthmap-*_output.html
        src/common/evaluation/QA/eval_depthmap_models/height/*.csv
        src/common/evaluation/QA/eval-standardisation-test/standardisation-test_output.html
        src/common/evaluation/QA/eval-standardisation-test/*.csv
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'Output Results'
      publishLocation: 'pipeline'
    displayName: 'Publish Results and Output Results'

  - bash: |
      az logout
    displayName: 'Azure Logout'
